version: "3.7"

services:
    client:
        image: jlesage/firefox
        container_name: mitm_client
        restart: always
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "5800:5800"
        networks:
            mitm:
                ipv4_address: 
    server:
        image: aikain/simplehttpserver:0.1
        container_name: mitm_server
        restart: always
        volumes:
            - ./server:/var/www
        networks:
            mitm:
                ipv4_address: 
    hacker:
        privileged: true
        build: .
        container_name: mitm_hacker
        volumes:
            - ./hacker:/hacks
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
            - net.ipv4.conf.all.send_redirects=0
        networks:
            mitm:
                ipv4_address: 

networks:
    mitm:
        ipam:
            config:
                - subnet: 192.168.0.0/24
