version: "3.7"

services:
    host:
        image: jlesage/firefox
        container_name: mitm_host
        restart: always
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "5800:5800"
        networks:
            - mitm
    messenger-client:
        image: aikain/simplehttpserver:0.1
        container_name: mitm_messenger-client
        restart: always
        volumes:
            - ./messenger-client:/var/www
        networks:
            - mitm
    hacker:
        privileged: true
        build: .
        container_name: mitm_hacker
        volumes:
            - ./hacker:/hacks
        sysctls:
            # Necessary for transparent mode for mitmproxy
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
            - net.ipv4.conf.all.send_redirects=0
        networks:
            - mitm

networks:
    mitm:
